### PR TITLE
Feat/adjust header to mobile

### PR DESCRIPTION
**Pull request by rozanagy**
Overview: This pull request implements responsive design adjustments to the header component of the application, ensuring an optimized user experience on mobile devices. The changes are aimed at enhancing usability and maintaining aesthetic consistency across different screen sizes.

Responsive Layout Implementation:

Modified the header layout using Chakra UI's responsive utilities to ensure that elements stack appropriately on smaller screens.
Ensured the header adapts to various breakpoints for a seamless transition between mobile and desktop views.
Hamburger Menu Integration:

Introduced a hamburger menu icon that consolidates navigation options, allowing users to access the menu without taking up excessive screen space.
The menu expands on click, providing access to all navigation items in a clean and organized manner.

### CODE REVIEW

**Comment by rozanagy** [comment]
https://github.com/user-attachments/assets/18db2a4c-fb3e-4d1d-aa01-573c731b8c17

**Review by Polybius93 — CHANGES_REQUESTED** [review]
Generally really good, some things I noticed in the video:
- When you log in, the dlcBTC logo becomes larger than before
- Let's change the color scheme of the right side menu button to something that matches the desktop button's color scheme, this is also a request for the dropdown.

**Comment by rozanagy** [comment]
https://github.com/user-attachments/assets/4cde73ed-230f-4ef0-88a4-caba8acc8839

**Review by Polybius93 — APPROVED** [review]
Nice job! Approved!

**Pull request merged**
